-- Agrega catalogo de LADAS (México)
CREATE TABLE IF NOT EXISTS ladas (
    lada VARCHAR(3) NOT NULL,
    estado VARCHAR(80) NOT NULL,
    ciudad VARCHAR(120) NOT NULL,
    pais VARCHAR(80) NOT NULL DEFAULT 'México',
    PRIMARY KEY (lada, estado, ciudad)
);

INSERT INTO ladas (lada, estado, ciudad, pais) VALUES
('55', 'CDMX', 'Ciudad de México', 'México'),
('56', 'CDMX', 'Ciudad de México', 'México'),
('722', 'Edo. Méx.', 'Toluca', 'México'),
('595', 'Edo. Méx.', 'Texcoco', 'México'),
('712', 'Edo. Méx.', 'Atlacomulco', 'México'),
('721', 'Edo. Méx.', 'Ixtapan de la Sal', 'México'),
('726', 'Edo. Méx.', 'Valle de Bravo', 'México'),
('591', 'Edo. Méx.', 'Zumpango', 'México'),
('33', 'Jalisco', 'Guadalajara', 'México'),
('322', 'Jalisco', 'Puerto Vallarta', 'México'),
('378', 'Jalisco', 'Tepatitlán', 'México'),
('317', 'Jalisco', 'Autlán', 'México'),
('341', 'Jalisco', 'Ciudad Guzmán', 'México'),
('474', 'Jalisco', 'Lagos de Moreno', 'México'),
('81', 'Nuevo León', 'Monterrey', 'México'),
('821', 'Nuevo León', 'Linares', 'México'),
('477', 'Guanajuato', 'León', 'México'),
('462', 'Guanajuato', 'Irapuato', 'México'),
('461', 'Guanajuato', 'Celaya', 'México'),
('464', 'Guanajuato', 'Salamanca', 'México'),
('473', 'Guanajuato', 'Guanajuato (capital)', 'México'),
('415', 'Guanajuato', 'San Miguel de Allende', 'México'),
('222', 'Puebla', 'Puebla', 'México'),
('238', 'Puebla', 'Tehuacán', 'México'),
('244', 'Puebla', 'Atlixco', 'México'),
('248', 'Puebla', 'San Martín Texmelucan', 'México'),
('229', 'Veracruz', 'Veracruz', 'México'),
('228', 'Veracruz', 'Xalapa', 'México'),
('271', 'Veracruz', 'Córdoba', 'México'),
('272', 'Veracruz', 'Orizaba', 'México'),
('782', 'Veracruz', 'Poza Rica', 'México'),
('921', 'Veracruz', 'Coatzacoalcos', 'México'),
('922', 'Veracruz', 'Minatitlán', 'México'),
('664', 'Baja California', 'Tijuana', 'México'),
('686', 'Baja California', 'Mexicali', 'México'),
('646', 'Baja California', 'Ensenada', 'México'),
('665', 'Baja California', 'Tecate', 'México'),
('612', 'BCS', 'La Paz', 'México'),
('624', 'BCS', 'Cabo San Lucas', 'México'),
('998', 'Quintana Roo', 'Cancún', 'México'),
('984', 'Quintana Roo', 'Playa del Carmen', 'México'),
('987', 'Quintana Roo', 'Cozumel', 'México'),
('983', 'Quintana Roo', 'Chetumal', 'México'),
('999', 'Yucatán', 'Mérida', 'México'),
('985', 'Yucatán', 'Valladolid', 'México'),
('969', 'Yucatán', 'Progreso', 'México'),
('614', 'Chihuahua', 'Chihuahua', 'México'),
('656', 'Chihuahua', 'Ciudad Juárez', 'México'),
('639', 'Chihuahua', 'Delicias', 'México'),
('625', 'Chihuahua', 'Cuauhtémoc', 'México'),
('662', 'Sonora', 'Hermosillo', 'México'),
('631', 'Sonora', 'Nogales', 'México'),
('653', 'Sonora', 'San Luis Río Colorado', 'México'),
('622', 'Sonora', 'Guaymas', 'México'),
('642', 'Sonora', 'Navojoa', 'México'),
('899', 'Tamaulipas', 'Reynosa', 'México'),
('868', 'Tamaulipas', 'Matamoros', 'México'),
('867', 'Tamaulipas', 'Nuevo Laredo', 'México'),
('833', 'Tamaulipas', 'Tampico', 'México'),
('834', 'Tamaulipas', 'Ciudad Victoria', 'México'),
('844', 'Coahuila', 'Saltillo', 'México'),
('871', 'Coahuila', 'Torreón', 'México'),
('866', 'Coahuila', 'Monclova', 'México'),
('878', 'Coahuila', 'Piedras Negras', 'México'),
('777', 'Morelos', 'Cuernavaca', 'México'),
('735', 'Morelos', 'Cuautla', 'México'),
('771', 'Hidalgo', 'Pachuca', 'México'),
('775', 'Hidalgo', 'Tulancingo', 'México'),
('773', 'Hidalgo', 'Tula', 'México'),
('744', 'Guerrero', 'Acapulco', 'México'),
('747', 'Guerrero', 'Chilpancingo', 'México'),
('733', 'Guerrero', 'Iguala', 'México'),
('755', 'Guerrero', 'Zihuatanejo', 'México'),
('951', 'Oaxaca', 'Oaxaca de Juárez', 'México'),
('971', 'Oaxaca', 'Salina Cruz', 'México'),
('287', 'Oaxaca', 'Tuxtepec', 'México'),
('961', 'Chiapas', 'Tuxtla Gutiérrez', 'México'),
('962', 'Chiapas', 'Tapachula', 'México'),
('967', 'Chiapas', 'San Cristóbal', 'México'),
('963', 'Chiapas', 'Comitán', 'México')
ON CONFLICT (lada, estado, ciudad) DO NOTHING;
